// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV8O92zp1HNWT6060M2Mae8OZ5h_I-HEs',
    appId: '1:957626042083:web:18a01d2bb4f94c166167d6',
    messagingSenderId: '957626042083',
    projectId: 'vemientay-6c26c',
    authDomain: 'vemientay-6c26c.firebaseapp.com',
    databaseURL:
        'https://vemientay-6c26c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vemientay-6c26c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMO5FNTS-vLqrcv2JaQk0SGQ1Bok_jLYU',
    appId: '1:957626042083:android:3f1ff463aaacf2e76167d6',
    messagingSenderId: '957626042083',
    projectId: 'vemientay-6c26c',
    databaseURL:
        'https://vemientay-6c26c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vemientay-6c26c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9mGmP0lv1Pz26xB72vf6pE2MS-PwRgMc',
    appId: '1:957626042083:ios:dfcc0c0e12660c176167d6',
    messagingSenderId: '957626042083',
    projectId: 'vemientay-6c26c',
    databaseURL:
        'https://vemientay-6c26c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vemientay-6c26c.appspot.com',
    iosClientId:
        '957626042083-mon9sq05gn85np5lap41pv0gb9oodig5.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingTransitionFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9mGmP0lv1Pz26xB72vf6pE2MS-PwRgMc',
    appId: '1:957626042083:ios:0b1a2558a9d952026167d6',
    messagingSenderId: '957626042083',
    projectId: 'vemientay-6c26c',
    databaseURL:
        'https://vemientay-6c26c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vemientay-6c26c.appspot.com',
    iosClientId:
        '957626042083-shr0spbusc3lon4l4utt6vvl5culs6c2.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingTransitionFlutter.RunnerTests',
  );
}
